services:
  redis:
    image: redis:8.2.1-alpine
    restart: always
    command: redis-server --maxmemory-policy noeviction
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7.0.5
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
